<?php
defined('BASEPATH') OR exit('No direct script access allowed');
$config['num_links'] = 2;
$config['use_page_numbers'] = TRUE;
$config['page_query_string'] = TRUE;
$config['query_string_segment'] = 'page';
$config['first_link'] = '<i class="fas fa-angle-left"></i>';
$config['last_link'] = '<i class="fas fa-angle-right"></i>';
$config['full_tag_open'] = "<ul class='pagination'>";
$config['full_tag_close'] = "</ul>";
$config['num_tag_open'] = '<li class="page-link">';
$config['num_tag_close'] = '</li>';
$config['cur_tag_open'] = "<li class='page-item'><li class='page-item active'><a class='page-link' href='#'>";
$config['cur_tag_close'] = "<span class='sr-only'></span></a></li>";
$config['next_link'] = '<i class="fas fa-angle-right"></i>';
$config['next_tag_open'] = "<li class='page-link'>";
$config['next_tagl_close'] = "</li>";
$config['prev_link'] = '<i class="fas fa-angle-left"></i>';
$config['prev_tag_open'] = "<li class='page-link'>";
$config['prev_tagl_close'] = "</li>";
$config['first_tag_open'] = "<li class='page-link'>";
$config['first_tagl_close'] = "</li>";
$config['last_tag_open'] = "<li class='page-link'>";
$config['last_tagl_close'] = "</li>";